### ISSUE TITLE
Linux build fails without visible error message

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/google-cloud-storage-feedstock#1]
@conda-forge/core, CircleCI fails without an obvious error message:
```
./ci_support/run_docker_build.sh

Containers: 0
Images: 20
Server Version: 1.9.1-circleci-cp-workaround
Storage Driver: btrfs
Execution Driver: lxc-1.0.9
Logging Driver: json-file
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 2
Total Memory: 58.97 GiB
Name: box39
ID: ZRH7:HMPP:BSJ5:4FAI:4NCG:FHJ4:SLCU:5OUM:G3YX:UODB:NVWJ:H6H5
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 18
 System Time: 2017-06-23T08:08:39.44175704Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

./ci_support/run_docker_build.sh returned exit code 1
```

Is this a known issue in the build system? Any idea what might be wrong or how to fix it?

**Comment by johanneskoester** [comment]
Trying to rerender the feedstock leads to the following error:
```
conda smithy regenerate --feedstock_directory .
Fetching package metadata ...........
Traceback (most recent call last):
  File "/home/johannes/.local/opt/miniconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 283, in main
    args.subcommand_func(args)
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 188, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 709, in main
    render_circle(env, config, forge_dir)
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_circle
    forge_config.get('channels', {}).get('sources', tuple())
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 628, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/home/johannes/.local/opt/miniconda/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 223, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
KeyError: 'python-3.3.0-pro0.tar.bz2'
```
Happens also when setting conda-forge as the only channel.

**Comment by patricksnape** [comment]
Circleci was down, should be resolved now
